# Generated by Django 5.2.7 on 2026-01-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_organizersubscriptionprice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizersubscriptionprice',
            options={},
        ),
        migrations.AddField(
            model_name='organizersubscription',
            name='paypal_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organizersubscription',
            name='paypal_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizersubscriptionprice',
            name='paypal_plan_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
