# Generated by Django 5.2.7 on 2026-01-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_organizersubscriptionprice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ORGANIZER', 'Organizer'), ('CLUB_MANAGER', 'Club Manager'), ('JUDGE', 'Judge'), ('ANONYMOUS', 'Anonymous')], default='ANONYMOUS', max_length=50),
        ),
    ]
