# Generated by Django 5.2.7 on 2025-11-12 00:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DJECA', 'Djeca'), ('JUNIORI', 'Juniori'), ('SENIORI', 'Seniori')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED_APPLICATIONS', 'Closed applications'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('starting_list_pdf', models.FileField(blank=True, null=True, upload_to='starting_lists/')),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999.99'))])),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionJudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
            ],
        ),
        migrations.CreateModel(
            name='GroupSizeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SOLO', 'Solo'), ('DUO', 'Duo'), ('MALA_GRUPA', 'Mala grupa'), ('FORMACIJA', 'Formacija')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StyleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BALET', 'Balet'), ('HIPHOP', 'Hip Hop'), ('JAZZ', 'Jazz'), ('STEP', 'Step'), ('BREAK', 'Break')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choreography', models.CharField(max_length=50)),
                ('length', models.DurationField()),
                ('choreograph', models.CharField(max_length=50)),
                ('music', models.FileField(blank=True, null=True, upload_to='')),
                ('paid_registration', models.BooleanField(default=False)),
                ('age_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competitions.agecategory')),
            ],
        ),
    ]
