# Generated by Django 5.2.7 on 2026-01-19 16:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DJECA', 'Djeca'), ('JUNIORI', 'Juniori'), ('SENIORI', 'Seniori')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupSizeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SOLO', 'Solo'), ('DUO', 'Duo'), ('MALA_GRUPA', 'Mala grupa'), ('FORMACIJA', 'Formacija')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('mp3', 'Music'), ('pdf', 'Document')], max_length=10)),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StyleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BALET', 'Balet'), ('HIPHOP', 'Hip Hop'), ('JAZZ', 'Jazz'), ('STEP', 'Step'), ('BREAK', 'Break')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED_APPLICATIONS', 'Closed applications'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999.99'))])),
                ('age_categories', models.ManyToManyField(related_name='competitions', to='competitions.agecategory')),
                ('organizer', models.ForeignKey(limit_choices_to={'role': 'ORGANIZER'}, on_delete=django.db.models.deletion.CASCADE, related_name='organized_competitions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choreography', models.CharField(max_length=50)),
                ('length', models.DurationField()),
                ('choreograph', models.CharField(max_length=50)),
                ('accepted', models.BooleanField(default=False)),
                ('paid_registration', models.BooleanField(default=False)),
                ('age_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competitions.agecategory')),
                ('club_manager', models.ForeignKey(limit_choices_to={'role': 'CLUB_MANAGER'}, on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to=settings.AUTH_USER_MODEL)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='competitions.competition')),
                ('group_size_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competitions.groupsizecategory')),
                ('music', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appearance_music', to='competitions.mediafile')),
                ('style_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competitions.stylecategory')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionJudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_judges', to='competitions.competition')),
                ('judge', models.ForeignKey(limit_choices_to={'role': 'JUDGE'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_competitions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='judges',
            field=models.ManyToManyField(related_name='judged_competitions', through='competitions.CompetitionJudge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('appearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='competitions.appearance')),
                ('judge', models.ForeignKey(limit_choices_to={'role': 'JUDGE'}, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='group_size_categories',
            field=models.ManyToManyField(related_name='competitions', to='competitions.groupsizecategory'),
        ),
        migrations.AddField(
            model_name='competition',
            name='starting_list',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_starting_list', to='competitions.mediafile'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('appearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='competitions.appearance')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='competitions.competition')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='style_categories',
            field=models.ManyToManyField(related_name='competitions', to='competitions.stylecategory'),
        ),
        migrations.AddConstraint(
            model_name='competitionjudge',
            constraint=models.UniqueConstraint(fields=('judge', 'competition'), name='unique_judge_competition'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('judge', 'appearance'), name='unique_judge_appearance'),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('competition', 'appearance')},
        ),
    ]
