# Generated by Django 5.2.7 on 2025-11-12 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='club_manager',
            field=models.ForeignKey(limit_choices_to={'role': 'CLUB MANAGER'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competition',
            name='age_categories',
            field=models.ManyToManyField(related_name='competitions', to='competitions.agecategory'),
        ),
        migrations.AddField(
            model_name='competition',
            name='organizer',
            field=models.ForeignKey(limit_choices_to={'role': 'ORGANIZER'}, on_delete=django.db.models.deletion.CASCADE, related_name='organized_competitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appearance',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='competitions.competition'),
        ),
        migrations.AddField(
            model_name='competitionjudge',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_judges', to='competitions.competition'),
        ),
        migrations.AddField(
            model_name='competitionjudge',
            name='judge',
            field=models.ForeignKey(limit_choices_to={'role': 'JUDGE'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_competitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competition',
            name='judges',
            field=models.ManyToManyField(related_name='judged_competitions', through='competitions.CompetitionJudge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='appearance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='competitions.appearance'),
        ),
        migrations.AddField(
            model_name='grade',
            name='judge',
            field=models.ForeignKey(limit_choices_to={'role': 'JUDGE'}, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competition',
            name='group_size_categories',
            field=models.ManyToManyField(related_name='competitions', to='competitions.groupsizecategory'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='group_size_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competitions.groupsizecategory'),
        ),
        migrations.AddField(
            model_name='competition',
            name='style_categories',
            field=models.ManyToManyField(related_name='competitions', to='competitions.stylecategory'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='style_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competitions.stylecategory'),
        ),
        migrations.AddConstraint(
            model_name='competitionjudge',
            constraint=models.UniqueConstraint(fields=('judge', 'competition'), name='unique_judge_competition'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('judge', 'appearance'), name='unique_judge_appearance'),
        ),
    ]
