# Generated by Django 5.2.7 on 2026-01-13 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('mp3', 'Music'), ('pdf', 'Document')], max_length=10)),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='competition',
            name='starting_list_pdf',
        ),
        migrations.AlterField(
            model_name='appearance',
            name='club_manager',
            field=models.ForeignKey(limit_choices_to={'role': 'CLUB_MANAGER'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competition',
            name='starting_list',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_starting_list', to='competitions.mediafile'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='music',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appearance_music', to='competitions.mediafile'),
        ),
    ]
